# Generated by Django 4.0 on 2022-01-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('genre_photo', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ('genre_name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_info', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genres')),
            ],
            options={
                'ordering': ('genre_info',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
