# Generated by Django 4.0 on 2022-01-05 15:38

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название медианосителя')),
            ],
            options={
                'verbose_name': 'Медианоситель',
                'verbose_name_plural': 'Медианосители',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя музыканта')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function)),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterIndexTogether(
            name='genre',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='Описание появится позже', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название жанра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('use_in_slider', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея изображений',
                'verbose_name_plural': 'Галерея изображений',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель/группа')),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='Описание появится позже', verbose_name='Описание')),
                ('exist_data', models.DateField(verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('members', models.ManyToManyField(related_name='artist', to='music.Member', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('songs_list', models.TextField(verbose_name='Трэклист')),
                ('release_data', models.DateField(verbose_name='Дата релиза')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_info',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
    ]
