# Generated by Django 4.0 on 2022-01-07 11:54

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_artist_exist_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function),
        ),
    ]
