# Generated by Django 4.0 on 2022-01-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_artist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
