# Generated by Django 4.0 on 2022-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_genre_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField()),
                ('anons', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('description', models.TextField(default='Текст появится позже', verbose_name='Текст новости')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
